#!/usr/bin/env sh
# setvol -- run pactl set-sink-volume on running sinks
set -o errexit
set -o nounset

# set volume of RUNNING sinks
pactl list short sinks \
    | grep RUNNING \
    | cut -f1 \
    | xargs -I {} pactl set-sink-volume {} "$1"
