#!/usr/bin/env sh
# watchdir -- run a command every time a file in a directory tree is modified
set -o errexit
set -o nounset

watchpath=$1
shift

$@
while inotifywait -qq --recursive --event modify "$watchpath"
do
    echo
    $@
done
