#!/usr/bin/env bash
# xstatus -- daemon for setting the X root window name
set -o nounset

pidfile="${XDG_CACHE_HOME:-$HOME/.cache}"/xstatus.pid
if ps -p "$(cat "$pidfile")" &>/dev/null; then
    echo "Already running, sending refresh signal..."
    kill -USR1 "$(cat "$pidfile")"
    exit
else
    echo "Writing PID $$ to '$pidfile'"
    echo $$ >"$pidfile"
fi

# instant refresh on USR1 (because wait is interrupted in main loop)
trap 'true' USR1

update_interval=5  # how often to run main loops (seconds)
checkupdates_interval=15  # how often to refresh checkupdates data (minutes)
crypto_interval=15  # how often to refresh cryptocurrency data (minutes)
crypto_tickers=(bitcoin litecoin ethereum nano)  # CoinMarketCap tickers
date_format='+%a (W%V) %Y-%m-%d %H:%M'

# create temporary files to cache online data
temp_dir=$(mktemp -d --tmpdir xstatus.XXXXXXXXXX)
update_file=$(mktemp -p "$temp_dir" updates.XXXXXXXXXX)
declare -A crypto_files
for ticker in "${crypto_tickers[@]}"; do
    crypto_files[$ticker]=$(mktemp -p "$temp_dir" crypto.XXXXXXXXXX)
done

tempfiles=("$update_file" "${crypto_files[@]}")
trap "rm ${tempfiles[*]@Q} && rmdir '$temp_dir'" EXIT

# exit with 0 if file is empty or older than $minutes
function file_expired {
    file=$1
    minutes=$2
    [ ! -s "$file" ] || [ -n "$(find "$file" -mmin +"$minutes")" ]
}

# online data refresh loop
( while :; do
    # don't do anything without a network connection
    if ! checknetwork; then
        sleep $update_interval
        continue
    fi

    # check for updates if we last checked more than $checkupdates_interval
    # minutes ago, or if pacman was run after that
    if file_expired "$update_file" "$checkupdates_interval" \
            || [ /var/log/pacman.log -nt "$update_file" ]; then
        # fetch updates to a temp file first, only overwriting on success
        # this avoids erasing $update_file if checkupdates/aurupdate fails
        temp_update_file=$(mktemp)

        if checkupdates >"$temp_update_file" \
                && aurupdate -l ~/aur >>"$temp_update_file"; then
            cat <(echo 'Updates:') "$temp_update_file" >"$update_file"
        fi
        rm "$temp_update_file"
    fi

    # update crypto tickers if data is expired or not valid
    for ticker in "${crypto_tickers[@]}"; do
        crypto_file="${crypto_files[$ticker]}"
        if file_expired "$crypto_file" "$crypto_interval" \
                || ! jq --exit-status . >/dev/null "$crypto_file"; then
            curl -fsSLo "${crypto_files[$ticker]}" \
                "https://api.coinmarketcap.com/v1/ticker/$ticker" || true
        fi
    done

    sleep $update_interval
done ) &

function wifi_status {
    wifi=$(iw dev | grep ssid | sed 's/\s*ssid\s//')
    if [ -z "$wifi" ]; then
        wifi='Disconnected'
    fi

    if pidof openvpn >/dev/null || pidof openconnect >/dev/null; then
        wifi="$wifi (VPN)"
    fi

    echo "$wifi"
}

# format a CoinMarketCap JSON file as a status bar string
function crypto_status {
    # extract $symbol, $price, $change, $timestamp
    eval "$(jq -r '@sh "
        symbol=\(.[0].symbol)
        price=\(.[0].price_usd)
        change=\(.[0].percent_change_24h)
        timestamp=\(.[0].last_updated)"' "$1")"
    [ -z "${symbol+x}" ] && exit  # exit if symbol is unset

    [[ "$change" =~ ^- ]] && dir='▼' || dir='▲';

    # format timestamp in a human-friendly way
    delta=$(( $(date +%s)-timestamp ))
    if [ "$delta" -ge 86400 ]; then
        age="$(( delta/86400 ))d"
    elif [ "$delta" -ge 3600 ]; then
        age="$(( delta/3600 ))h"
    elif [ "$delta" -ge 60 ]; then
        age="$(( delta/60 ))m"
    else
        age="${delta}s"
    fi

    printf "%s \$%.2f %s %+.1f%% (%s)" "$symbol" "$price" "$dir" "$change" "$age"
}

function volume_status {
    volume="$(pamixer --get-volume)"
    if [ "$(pamixer --get-mute)" = true ]; then
        speaker='🔇'
    elif [ "$volume" -gt 50 ]; then
        speaker='🔊'
    elif [ "$volume" -gt 0 ]; then
        speaker='🔉'
    else
        speaker='🔈'
    fi

    echo "$speaker$volume%"
}

# update status text
crypto_index=0
function refresh_xroot {
    date=$(date "$date_format")
    battery=$(acpi --battery | sed 's/Battery 0: //g')
    wifi=$(wifi_status)
    volume=$(volume_status)
    emails=$(cut -d: -f1 ~/.thunderbird/*/unread-counts | paste -sd+ - | bc)
    update_count=$(( $(wc -l <"$update_file") - 1 ))

    # cycle through tickers
    crypto_file="${crypto_files[${crypto_tickers[crypto_index % ${#crypto_tickers[@]}]}]}"
    crypto_status=$(crypto_status "$crypto_file")

    root="$wifi | $battery | $volume | $date"
    [ "$update_count" -gt 0 ] && root="${update_count}⇅ | $root"
    [ "$emails" -gt 0 ] && root="${emails}✉ | $root"
    [ -n "$crypto_status" ] && root="$crypto_status | $root"

    xsetroot -name "$root"
}

while :; do
    crypto_index=$((crypto_index+1))
    refresh_xroot
    sleep $update_interval &
    wait $!
done
